name: covid19_tracker
description: Track all data of Corona Virus around the World.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.5+1

environment:
    sdk: '>=2.2.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    google_nav_bar: ^2.1.0
    mobx: ^1.1.1
    flutter_mobx: ^1.1.0
    geolocator: ^5.3.1
    flutter_neumorphic: ^1.0.3+1
    google_fonts: ^0.3.10
    flutter_echarts:
        path: ./flutter_echarts
    dio: ^3.0.9
    intl: ^0.16.1
    line_awesome_icons:
    connectivity: ^0.4.8+2
    shared_preferences: ^0.5.6+3
    package_info: ^0.4.0+16
    url_launcher: ^5.4.2
    flutter_webview_plugin:
    esys_flutter_share: ^1.0.2
    path_provider: ^1.6.7
    permission_handler: ^5.0.0+hotfix.4
    install_plugin:
        path: ./install_plugin
    system_info: ^0.1.3
    expandable: ^4.1.3
    sliding_panel: ^1.2.2


    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^0.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^1.8.1
    mobx_codegen: ^1.0.3
    flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  adaptive_icon_padding: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true
    # To add assets to your application, add an assets section, like this:
    assets:
     - assets/images/developer.jpeg
     - assets/images/no-internet.png
     - assets/images/update.png
     - assets/images/no-location.png
     - assets/icon/ic_launcher.png
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
